### ISSUE TITLE
Project Entry in List View

### ISSUE THREAD

**Issue by JJediny** [DOE-NEPA/mapwarper#4]
- [ ] Make "Download KML" link appear before "is a map" pull down in same line as the rest
- [ ] Change "Source/Bib Ref" to "Project Webpage on Energy.gov" 
- [ ] Add metadata entry for another link as some projects have their own website use "Project Website" separated by | in list layout
  ![image](https://cloud.githubusercontent.com/assets/6350035/6101278/68d80732-afef-11e4-8a53-6550142c33cc.png)

**Comment by eisemann** [comment]
Hey John,
I updated the list views (e.g. http://ec2-54-88-210-186.compute-1.amazonaws.com/maps) so that those controls are no longer displayed.  All of the functionality still exists when you view the actual map.  I thought that de-cluttering the list views would make them more readable and easier to use but can add the controls back in if you want.  What do you think?
